# Формат чата. Можно использовать:
# - %player_name% как имя игрока (пример PlaceholderAPI: %player_name% или любой другой плейсхолдер)
# - %message% для самого сообщения
# - Любые плейсхолдеры PlaceholderAPI

# Раздел локального чата
local-chat:
  enabled: true            # Включён ли локальный чат
  radius: 70               # Радиус (в блоках), в пределах которого видны сообщения
  format: "&#ffffff[LOCAL] %player_name%: %message%"

# Раздел глобального чата
global-chat:
  enabled: true
  prefix: "!"              # Префикс, с которого начинается сообщение в глобальном чате
  format: "&#ffaa00[GLOBAL] %player_name%: %message%"

# Личные сообщения
private-chat:
  enabled: true
  format-sender: "&#55FFFF[-> %target_name%] %message%"
  format-receiver: "&#55FFFF[%player_name% -> You] %message%"

  usage-message:
    - "&7--------------------------------"
    - "&eИспользование: &f/m <ник_игрока> <сообщение>"
    - "&7--------------------------------"

  offline-player-message:
    - "&7--------------------------------"
    - "&cИгрок &f%target_name% &cне в сети!"
    - "&7Проверьте правильность ника."
    - "&7--------------------------------"

hex-colors: true

# Список строк, который будет показан при наведении на ник (hover).
# Можем использовать PlaceholderAPI-плейсхолдеры вроде %player_level%.
# Строки соединятся переводом строки (\n).
# Настройки упоминаний

mention:
  # Как будем выделять упоминания в чате
  # Можно использовать формат Adventure/Legacy (превратим & + § + hex),
  # здесь важны "&#ff5e0d" для цвета + "&l" для жирного
  highlight-format: "&#ff5e0d&l@%mention%&r"
  # Звук, который будет проигрываться упомянутому игроку
  sound: "minecraft:block.note_block.pling"

# Список строк, показываемых в hover при наведении на НИК отправителя
hover-text:
  - "&eИгрок: &f%player_name%"
  - "&7Нажмите, чтобы написать &f/m %player_name%"
  - "&7Локальные координаты: &f%player_x% %player_y% %player_z%"

# Системные сообщения (пример)
system-messages:
  player-not-found: "&cИгрок &f@%mention% &cне найден или офлайн!"
  reload-success:
    - "&aКонфиг CloverChat успешно перезагружен!"
    - "&7Вы можете продолжить настройку."

# Новые блоки:
commands-cooldown:
  enabled: true
  seconds: 5
  message:
    - "&cВы слишком быстро вводите команды!"
    - "&7Подождите &f%remain% &7секунд прежде, чем использовать другую команду."

no-chat-permission-message:
  - "&cУ вас нет прав, чтобы писать в чат!"
  - "&7Обратитесь к администратору."

links:
  enabled: true
  format: "*ссылка*"
  hover-lines:
    - "&7URL: &f%url%"
    - "&eВторая строка"
    - "&cМожно добавлять &bнесколько &eстрок"

join-message:
  enabled: true
  text: "&#55FF55[+] %player_name% зашёл на сервер!"

leave-message:
  enabled: true
  text: "&#FF5555[-] %player_name% вышел с сервера!"

censor:
  enabled: true
  words:
    - "херня"
    - "хрен"
    - "дурак"
    - "дура"