name: CloverChat
version: 1.0
main: com.fread.CloverChat.CloverChat
api-version: 1.16
author: fread
depend: [PlaceholderAPI, ProtocolLib]
description: Настраиваемый чат

commands:
  m:
    description: Отправить личное сообщение
    usage: /m <ник_игрока> <сообщение>
    permission: cloverchat.pm
    permission-message: "&cУ вас нет прав на использование этой команды!"

  cloverchatreload:
    description: Перезагрузить CloverChat
    usage: /cloverchatreload
    permission: cloverchat.command.reload
    permission-message: "&cУ вас нет прав на использование этой команды!"

permissions:
  cloverchat.chat.use:
    description: "Позволяет игроку писать в чат"
    default: true
  cloverchat.commandcooldown.bypass:
    description: "Позволяет обходить общий кулдаун на ввод команд"
    default: op
  cloverchat.pm:
    description: "Позволяет использовать личные сообщения /m"
    default: true
  cloverchat.command.reload:
    description: "Позволяет перезагружать плагин CloverChat"
    default: op